NEXTG-73 - create password api
bepatient-fr/patient-study-recruitment pull request #13
Opened 2023-02-24 16:42 UTC by abennani15

https://alirahealth-engineering.atlassian.net/browse/NEXTG-73

2023-02-27 17:10 UTC, akram-ayadi requested changes

2023-02-27 17:20 UTC, abennani15 commented on pages/create-password.tsx
> +				<CircularProgress />
Oui, c'est le background qui doit changer de couleur, cela est fait dans la PR du redesign.

2023-02-27 17:23 UTC, abennani15 commented on src/hooks/useAuth.ts
> +				console.error(error);
Oui, on n'a rien pour tracer les erreurs pour l'instant, donc vaut mieux la console que perdre l'erreur.

2023-02-28 08:52 UTC, akram-ayadi approved these changes

2023-02-28 10:18 UTC, merged