NEXTG-24 - Login / Reset password / Create password
bepatient-fr/patient-study-recruitment pull request #3
Opened 2023-02-16 10:39 UTC by abennani15

https://alirahealth-engineering.atlassian.net/browse/NEXTG-24

2023-02-16 17:22 UTC, akram-ayadi requested changes

2023-02-16 17:22 UTC, akram-ayadi commented on src/components/PasswordWithConfirm/PasswordWithConfirm.tsx
> +					Create password
Pour le titre du bouton, je pense qu'on doit différencier le cas du `Create password` de celui du `Reset password`

2023-02-16 17:22 UTC, akram-ayadi commented on src/components/PasswordWithConfirm/PasswordWithConfirm.tsx
> +					<FormHelperText text={!password || passwordChecker.isValid ? "" : "Password doesn’t meet requirements."} />
On peut pas afficher l'erreur que lorsqu'on quitte le champ ?

2023-02-16 17:22 UTC, akram-ayadi commented on src/components/PasswordWithConfirm/PasswordWithConfirm.tsx
> +					<FormHelperText text={password !== passwordConfirmation ? "Password doesn’t match" : ""} />
On rajoute dans la condition que le champs a été touché, non ?

2023-02-16 17:22 UTC, akram-ayadi commented on src/usecases/passwordChecker.ts
> +			isMin1Lowercase: regexAtLeastOneLowecase.test(password),
T'as juste une petite faute d'orthographe ici `regexAtLeastOneLowercase`

2023-02-17 10:12 UTC, abennani15 commented on src/components/PasswordWithConfirm/PasswordWithConfirm.tsx
> +					<FormHelperText text={!password || passwordChecker.isValid ? "" : "Password doesn’t meet requirements."} />
Les specs / designs ne disent rien sur cela pour le moment, on verra quand on aura un retour du produit.

2023-02-17 13:17 UTC, akram-ayadi approved these changes

2023-02-17 13:18 UTC, merged